Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
Exception while resolving variable 'form' in template 'users/login.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [form] in u"[{'False': False, 'None': None, 'True': True}]"
(0.015) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SELECT VERSION(); args=None
(0.041) SELECT `users_newuser`.`id`, `users_newuser`.`password`, `users_newuser`.`last_login`, `users_newuser`.`is_superuser`, `users_newuser`.`username`, `users_newuser`.`first_name`, `users_newuser`.`last_name`, `users_newuser`.`email`, `users_newuser`.`is_staff`, `users_newuser`.`is_active`, `users_newuser`.`date_joined`, `users_newuser`.`pwd`, `users_newuser`.`phone`, `users_newuser`.`session`, `users_newuser`.`level`, `users_newuser`.`is_pref`, `users_newuser`.`num_following`, `users_newuser`.`num_followed` FROM `users_newuser` WHERE `users_newuser`.`id` = 1; args=(1,)
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SELECT VERSION(); args=None
(0.001) SELECT `users_newuser`.`id`, `users_newuser`.`password`, `users_newuser`.`last_login`, `users_newuser`.`is_superuser`, `users_newuser`.`username`, `users_newuser`.`first_name`, `users_newuser`.`last_name`, `users_newuser`.`email`, `users_newuser`.`is_staff`, `users_newuser`.`is_active`, `users_newuser`.`date_joined`, `users_newuser`.`pwd`, `users_newuser`.`phone`, `users_newuser`.`session`, `users_newuser`.`level`, `users_newuser`.`is_pref`, `users_newuser`.`num_following`, `users_newuser`.`num_followed` FROM `users_newuser` WHERE `users_newuser`.`id` = 1; args=(1,)
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'is_login' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_login] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SELECT `users_newuser`.`id`, `users_newuser`.`password`, `users_newuser`.`last_login`, `users_newuser`.`is_superuser`, `users_newuser`.`username`, `users_newuser`.`first_name`, `users_newuser`.`last_name`, `users_newuser`.`email`, `users_newuser`.`is_staff`, `users_newuser`.`is_active`, `users_newuser`.`date_joined`, `users_newuser`.`pwd`, `users_newuser`.`phone`, `users_newuser`.`session`, `users_newuser`.`level`, `users_newuser`.`is_pref`, `users_newuser`.`num_following`, `users_newuser`.`num_followed` FROM `users_newuser` WHERE `users_newuser`.`id` = 1; args=(1,)
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'is_login' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_login] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SELECT VERSION(); args=None
(0.000) SELECT `users_newuser`.`id`, `users_newuser`.`password`, `users_newuser`.`last_login`, `users_newuser`.`is_superuser`, `users_newuser`.`username`, `users_newuser`.`first_name`, `users_newuser`.`last_name`, `users_newuser`.`email`, `users_newuser`.`is_staff`, `users_newuser`.`is_active`, `users_newuser`.`date_joined`, `users_newuser`.`pwd`, `users_newuser`.`phone`, `users_newuser`.`session`, `users_newuser`.`level`, `users_newuser`.`is_pref`, `users_newuser`.`num_following`, `users_newuser`.`num_followed` FROM `users_newuser` WHERE `users_newuser`.`id` = 1; args=(1,)
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'is_login' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_login] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
(0.000) SELECT @@SQL_AUTO_IS_NULL; args=None
(0.000) SELECT VERSION(); args=None
(0.001) SELECT `users_newuser`.`id`, `users_newuser`.`password`, `users_newuser`.`last_login`, `users_newuser`.`is_superuser`, `users_newuser`.`username`, `users_newuser`.`first_name`, `users_newuser`.`last_name`, `users_newuser`.`email`, `users_newuser`.`is_staff`, `users_newuser`.`is_active`, `users_newuser`.`date_joined`, `users_newuser`.`pwd`, `users_newuser`.`phone`, `users_newuser`.`session`, `users_newuser`.`level`, `users_newuser`.`is_pref`, `users_newuser`.`num_following`, `users_newuser`.`num_followed` FROM `users_newuser` WHERE `users_newuser`.`id` = 1; args=(1,)
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'is_login' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [is_login] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
Exception while resolving variable 'request' in template 'users/user_detail.html'.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/template/base.py", line 903, in _resolve_lookup
    (bit, current))  # missing attribute
VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {'user': <NewUser: admin>}]"
